blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    
    path('post/new/', views.post_new, name='post_new'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('', views.post_list, name='post_list'),    
    path('profile_edit/', views.profile_edit, name='profile_edit'),
    path('logout/', views.logout_view, name='logout'),
    path('post/<str:slug>/', views.post_detail, name='post_detail'),
    path('post-edit/<str:slug>/', views.post_edit, name='post_edit'),
    path('post_Category/<int:id>/', views.post_Category, name='post_Category'),
    path('post_Tag/<int:id>/', views.post_Tag, name='post_Tag'),
    path('post_author/<int:id>/', views.post_author, name='post_author'),
    # path('post_Published_date/<int:id>/', views.post_published_date, name='post_published_date'),


]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('blog.urls')),
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.utils import timezone
from autoslug import AutoSlugField

        

class User(AbstractUser):
    email = models.EmailField(unique = True)
    gender = models.CharField(max_length = 10)
    image = models.ImageField(upload_to='user_images/')
    phone_no = models.CharField(max_length = 10)
    
    def __str__(self):
            return "{}".format(self.email)

class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
            return self.name   

class Tag(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
            return self.name  
 
      

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    title = models.CharField(max_length=250)
    text = models.TextField()
    slug = AutoSlugField(populate_from='title', unique=True)
    featured_image = models.ImageField(upload_to='featured_images/', blank=True, null=True)
    thumbnail_image = models.ImageField(upload_to='thumbnail_images/', blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self): 
            return self.title + ' | ' + str(self.author)

class Comment(models.Model):          
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    email = models.EmailField(null=True , blank=True)
    name = models.CharField(max_length=250, null=True , blank=True)
    text = models.TextField(null=True , blank=True)
    # comment = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    parent = models.ForeignKey('self' , null=True , blank=True , on_delete=models.CASCADE , related_name='replies')
   
    class Meta:
       ordering=['-created_date']

    def __str__(self):
       return str(self.name) + ' comment ' + str(self.text)

    @property
    def children(self):
       return Comment.objects.filter(parent=self).reverse()

    @property
    def is_parent(self):
        if self.parent is None:
            return True
        return False


    

blog/forms.py
from django import forms
from .models import User

from .models import Post, Category, Tag, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text', 'category', 'tag', 'featured_image', 'thumbnail_image')

class UserForm(forms.ModelForm):
    password1 =forms.CharField(widget=forms.PasswordInput)
    password2 =forms.CharField(widget=forms.PasswordInput, label='confirm password')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.validationError("password do not match")
        return password2

    class Meta:
        model = User
        fields = ['username', 'image', 'first_name', 'last_name', 'gender', 'password1', 'password2', 'phone_no','email', ]

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

class ProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'image', 'first_name', 'last_name', 'gender', 'phone_no', 'email', ]

class ProfileEditForm(forms.ModelForm):
                
    class Meta:
        model = User
        fields = ['username', 'image', 'first_name', 'last_name', 'gender', 'phone_no', 'email', ]

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['name','email','text']
                
        

blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post, User
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import PostForm, UserForm, LoginForm, ProfileForm, CommentForm
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from .forms import ProfileEditForm
from .models import Category
from .models import Tag
# from .forms import ReplyForm
from .models import Comment


def post_list(request):
   posts = Post.objects.all()
   return render(request,'blog/post_list.html',{'posts': posts})

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm()
    comments = Comment.objects.filter(post=post)
    new_comment = None
    parent=None

    if request.method == 'POST':
       form = CommentForm(request.POST)
       if form.is_valid():
            try:
                parent = request.POST.get('comment_id')
                parent = Comment.objects.filter(id=parent).last()
            except:
                parent=None

            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.parent = parent
            new_comment.save()
            return redirect('blog:post_detail', slug=post.slug)
    else:
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'post': post, 'comments': comments, 'form': form, 'parent':parent})

def post_new(request):
    if request.method == "POST":
       form = PostForm(request.POST, request.FILES)
       if form.is_valid():
           post = form.save(commit=False)
           post.author = request.user
           post.published_date = timezone.now()
           post.save()
           return redirect('blog:post_detail', slug=post.slug)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.tag.set(form.cleaned_data.get('tag'))
            post.save()
            return redirect('blog:post_detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST,request.FILES)
        if  form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password1']
            user.password = make_password(passworCommentsd)
            user=form.save()
            login(request, user)
            return redirect('blog:login')
    else:
        form = UserForm()
    return render(request, 'blog/signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if  form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
               login(request, user)
            return redirect('blog:post_list')
            
        else:
            form = 'Invalid username or password'  
    else:
        form = LoginForm()
    return render(request, 'blog/login.html', {'form': form})


@login_required
def profile(request):
    user = User.objects.filter(id=request.user.id).last()
    return render(request, 'blog/profile.html', {'user':user})

@login_required
def profile_edit(request):
    user = User.objects.filter(id=request.user.id)
    if  request.method == 'POST':
        form = ProfileForm(request.POST,request.FILES ,instance=request.user)
        if form.is_valid():
           form.save()
        return redirect('blog:profile')
    else:
        form = ProfileForm(instance=request.user)
    return render(request, 'blog/profile_edit.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('blog:login')

def post_Category(request, id):
    posts = Post.objects.filter(category_id=id)
    return render(request, 'blog/post_list.html', {'posts':posts})

def post_Tag(request, id):
    posts = Post.objects.filter(tag__id=id)
    return render(request, 'blog/post_list.html', {'posts':posts})

def post_author(request, id):
    posts = Post.objects.filter(author__id=id)
    return render(request, 'blog/post_list.html', {'posts':posts})

# def post_Published_date(request, slug):
#     published = Post.objects.filter(published_date=slug).last()
#     posts = Post.objects.filter(published_date=published).all()
#     return render(request, 'blog/postdatefil.html', {'posts':posts})
        


        

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Django Girls blog</title> 
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

    </head>
    <body>
        <header class="page-header">
            <div class="container">
                <div class="d-flex">
                <div class="col-10">
                    <h1><a href="/">Django Girls Blog</a></h1>
                    <h1><a href="/">welcome addii...!!</a></h1>
                </div>
                <div class="col-2">
                    {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu">
                    {% include './icons/file-earmark-plus.svg' %}
                </a>
                <a href="{% url 'blog:profile' %}" class="top-menu">
                    {% include './icons/person-square.svg' %}
                </a>
                <a href="{% url 'blog:logout' %}" class="top-menu">
                    {% include './icons/person-x-fill.svg' %}
                </a>
                {% else %}
                <a href="{% url 'blog:signup' %}" class="top-menu">
                    {% include './icons/arrow-right-square-fill.svg' %}
                </a>
                <a href="{% url 'blog:login' %}" class="top-menu">
                    {% include './icons/box-arrow-in-up-right.svg' %}
                </a>
                {% endif %}
                </div>
                
            </div>
        </header>
        <main class="container">
            <div class="row">
                <div class="col">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </main>
        {%block script%}
        {% endblock %}
    </body>
</html>

blog/templates/blog/login.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Login</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
        <aside class="actions">
            <a class="btn btn-secondary" href="{% url 'blog:post_edit' slug=post.slug %}">
                {% include './icons/pencil-fill.svg' %}
            </a>
        </aside>
        {% if post.published_date %}
                 <time class="date">
                {{ post.published_date }}
                 </time>
             {% endif %}
        <div class="d-flex flex-row">
            <div class="p-2">
            {% if post.thumbnail_image %}
            <img class="rounded-circle" src="{{ post.thumbnail_image.url }}" style="width: 100px;
            height: 100px; object-fit: cover;" alt=" ThumbnailImage">
            {% endif %} 
            </div>
            <div class="p-2">
            <h2>{{ post.title }} </h2> 
            <p>category: {{ post.category.name}}</p><hr> 
            </div>
            <div class="p-2">
            <p><a href="{% url 'blog:post_author' id=post.author.id %}"> By:- {{ post.author }}</a></p>
            </div>
             
        </div>
            

             {% if post.featured_image %}
                 <img class="square square-lg" src="{{ post.featured_image.url }}" style="width: 1300px;
                   height: 500px; object-fit: cover;" alt=" FeaturedImage">
             {% endif %}
            
        <p>{{ post.text|linebreaksbr }}</p>
        <p>Tags: 
            {% for tag in post.tag.all %}
            <p><a href="{% url 'blog:post_Tag' id=tag.id %}"> {{ tag }}</a></p>
            {% endfor %}
        </p>
     

        <h2> Comments </h2>
    <div class="card">
     {% if user.is_authenticated %}
      <form action="" method="POST" id="main_form" class="comment_form">
            <div>
             <label for="comment">Type Comment here</label>
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary" type="submit">Post</button>
            </div>
      </form>
      {% else %} 
      <h2>You need to Login to comment</h2> 
      {% endif %}
    </div>
    <div class="card">
        {% for comment in comments %}
        {% if comment.is_parent %}
        <div class="comment" style="background-color: powderblue">
            <p class="info">{{ comment.name }} | {{ comment.email }}</p> 
                 {{ comment.text|linebreaks }} 

        {% for reply in comment.replies.all %}
            <p class="info">{{ reply.name }} | {{ reply.email }}</p> 
            <li>{{ reply.text }}</li>
         {% endfor %}

        <form action="" method="POST" id="main_form{{ forloop.counter }}" class="reply_form">
            {{ comment_form.as_p}}
            {% csrf_token %}
            {{form.as_p}}
            <input type="hidden" name="comment_id" value="{{comment.pk}}">
            <input class="btn btn-primary" type="submit" value="reply">
        </form>
        <button id="Mybtn" data-id="{{ forloop.counter }}" class="btn btn-primary Mybtn">reply here</button>
        </div>
            {% endif %}
            {%empty%}
            <h4>there are no comments yet.</h4>
        {% endfor %}
    </div>
    </article>
{% endblock %}
{%block script%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>

<script >
$(document).ready(function(){
    $('.reply_form').each(function(){
        $(this).toggle();
    })
    $('.Mybtn').click(function(){
        let data_id = $(this).attr('data-id');
        $('#main_form'+data_id).toggle();
  });
});   
</script>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    
    <div class="row">
        {% for post in posts %}
        <div class="col-sm-6">
        <div class="col-dm-">
        <div class="card">
            {% if post.thumbnail_image %}
                <img class="card-image-top" src="{{ post.thumbnail_image.url }}" style="width: 600px; height: 380px; object-fit: cover;" alt=" ThumbnailImage">
            {% endif %}
                <time class="date">
                    {{ post.published_date }}
                </time>
            <h2 class="card-title"><a href="{% url 'blog:post_detail' slug=post.slug %}">{{ post.title }}</a></h2>
            <p class="text-black"><a href="{% url 'blog:post_Category' id=post.category.id %}">category: {{ post.category.name}}</a></p>
            <p class="card-text">{{ post.text|truncatechars:200 }}</p>
        </div>
        </div>
        </div>
        {% endfor %}
    </div>
    
{% endblock %}

blog/templates/blog/profile.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="card">
  <div class="d-flex align-items-end flex-column">
  <a href="{% url 'blog:profile_edit' %}">Edit Profile</a>
  </div>

  <div class="d-flex justify-content-center">
  <h2>User Profile</h2>
  </div>

  <div class="d-flex justify-content-center">
  <div class="card">
  <div class="text-black">
    <image class="rounded-circle" src="{{ user.image.url }}"  alt="profile picture">
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>gender: {{ user.gender}}</p>
    <p>phone_no:{{user.phone_no}}</p>
  </div>
  </div>
  </div>
</div> 
 

{% endblock %}

blog/templates/blog/profile_edit.html
{% extends 'blog/base.html' %}
{% block content %}
<h2>Edit Profile</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Signup</h2>
    <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
    </form>
{% endblock %} 